title: "My Hugo Site"
description: "A simple site built with Hugo"
baseurl: ""  # Nếu sử dụng subpath, ví dụ: "/myrepo"
url: "https://7270-NguyenVietAnh.github.io"  # URL của bạn, thay `username` bằng tên tài khoản GitHub
theme: "KeepIt"  # Chọn theme bạn muốn sử dụng