title: "My Personal Site"
description: "My personal profile on GitHub Pages"

baseurl: ""
url: "https://7270-NguyenVietAnh.github.io"

remote_theme: Fastbyte01/KeepIt

plugins:
  - jekyll-remote-theme
